name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  updateServer:
    name: Update server
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: ${{ secrets.SCRIPT }}
